### ISSUE TITLE
not updating when app is in the background

### ISSUE THREAD

**Issue by supakdee** [owntracks/ios#498]
_**Updated as Dec 30, 2017**_
I changed the subject & description to be more precise.
I believe the issue is from Geoforce not working when the app is in the background.
(App post location properly as per significant change mode rule)

**Original Post:**
Hi,

My set up of Owntracks to publish privately to MQTT server (CloudMQTT) used to work well till recently.

Now I found that often Owntracks will not post location to MQTT server anymore.

Do you know why? And how to fix it?

By the way, Location is set as Always /// Background App Refresh = ON

Thanks.

**Comment by supakdee** [comment]
Additional information: once owntracks is active in foreground, it sends location almost instantly

**Comment by ckrey** [comment]
What do you mean? What do you expect? Which device do you use? Which backend do you use?

Works pretty well here

**Comment by supakdee** [comment]
What do you mean?
I believe with ios 11.2, owntracks in background (significant change mode) will not post location to MQTT server.
Once it's active in the foreground, it posts immediately.

What do you expect? 
I expect Owntracks to post location to MQTT server as it used to do in the past. (travelling a distance of at least 500 meters in 5 minutes)

Which device do you use? 
iphone 6s

Which backend do you use?
CloudMQTT then Home Assistant

**Comment by supakdee** [comment]
When the app is in foreground, geoforce works & post location immidiately

**Comment by ckrey** [comment]
We had a problem with some iPhone models on some iOS versions #504.
I think this has been fixed now. @supakdee  can you confirm this?

**Comment by supakdee** [comment]
Hi,
Problem is still there with latest version on iOS 11.3 on iPhone 6S
If I use other navigation app like Google Map, it would work ok.
But if just owntrack in background, it would do nothing

**Comment by ckrey** [comment]
Thanks, I noticed the same phenomenon: the app reports every 5 minutes / 500m when another app (e.g. navigation) is actively using location services, but doesn't if not.

Unfortunately, a lot of developers are experiencing the same problem with iOS 11.x.x 
These problems are logged with Apple, but it seems to be by design: https://forums.developer.apple.com/thread/86034

**Comment by dpmurphy** [comment]
That apple thread has been updated with a workaround, that they believe resolves the issue....just in case you hadn’t noticed

**Comment by ckrey** [comment]
Thanks for the hint. I will try the workaround for OwnTracks

**Comment by chupacabra71** [comment]
so, for a complete noob, how do i roll this patch onto my owntracks app?

**Comment by ckrey** [comment]
You will have to wait until we upload it to the Apple App Store

**Comment by jpmens** [comment]
And before anybody asks: this happens when the app is ready for submittal to the App Store. :-)

**Comment by kngharv** [comment]
I have been using Owntracks for years.  Hosting my own MQTT server on Amazon cloud.  I have no less than 7 devices on my server.

My family members use various devices.   

As of January 2019, iPhone 6 still doesn't update in the background (iOS 12.1.2) by default.  The Owntrack version is 9.9.3.   It seems that Owntracks need to be running in the background (i.e. launch Owntracks first, then put them in the background) in order for Owntracks to update the location in the background.

Situation is worse for iPhone 4 devices running iOS 8.x   Owntracks will only update location when Owntracks is running in the foreground.

iPhone 7 and iPhone 7plus update location information in the background as expected.  So are my android devices.  

I have checked and double checked that Owntracks has location access and allow to access to location all the time.  

What else I can do?

**Comment by jpmens** [comment]
We're glad you've been using OwnTracks for years.

Please help me understand: this sentence makes no sense to me:

> As of January 2019, iPhone 6 still doesn't update in the background (iOS 12.1.2) by default. The Owntrack version is 9.9.3. It seems that Owntracks need to be running in the background (i.e. launch Owntracks first, then put them in the background) in order for Owntracks to update the location in the background.

first you say it doesn't update in the background and then you say it does.

**Comment by DerGute** [comment]
i can confirm this behaviour on my wifes iphone. Same setting. iPhone 6s, latest iOS and latest owntracks version. When she starts owntracks it sents location immediately. but after a specific time the server does not receive any data until the owntracks app is launched again. 
I have a android device and can say, that in the android app there arent such problems like that.

Best regards

**Comment by socon** [comment]
New user here who is observing the same behavior.  I have 2x Iphone 7's and 2x iphone 8's all running ios 12.1.2 and owntracks 12.0.2 from the app store.  I have the two Iphone 7's out right now with the app running in the background and they are not reporting location.  Remote commands are enabled and they do not respond after anytime to reportLocation.  I know that if I were to open the app where they are, they will start reporting location.  But then will stop again after the app is put in the background.  (updates are set to significant changes mode)

**Comment by jkurelek** [comment]
I'll add my voice to those who are also experiencing this problem. Exactly as everyone has described, after a while location updates do not happen with the app running in the background.

iPhone 7, iOS version 13.3.1
Owntracks version 13.1.7

**Comment by ghr12** [comment]
Can confirm this is happening on:

User-Agent': 'OwnTracks/13.1.7 CFNetwork/1121.2.2 '
                                       'Darwin/19.3.0', (IOS 13.3.1
HTTP mode.

Iphone XR

App gets put in to foreground works fine.  after about 15 minutes seems to go to sleep/suspend and is never heard from again until App is put in to foreground

**Comment by MarvinSchenkel** [comment]
Yep me too. Using iOS 13.3 on an iPhone XS with owntracks in MQTT mode. Reporting location works fine for a while after opening the app, but suddenly stops reporting its location. I am in move monitoring mode. @ckrey could you please re-open this issue?

**Comment by jpmens** [comment]
@MarvinSchenkel works as expected and documented: in move mode, the app must be in the foreground https://owntracks.org/booklet/features/location/

**Comment by GitHubQueenn** [comment]
> @MarvinSchenkel works as expected and documented: in move mode, the app must be in the foreground https://owntracks.org/booklet/features/location/

Hi, is this still the case? The whole point of me using this was to use Move mode so it's constantly updating location (whole point of app?) on my friend, vice-versa. It works for me, on Android, but on their iPhone, it's only working when the app is opened and then a few secs/mins when they leave the app. Their phone location settings for the app are also properly set to Always Allow. Any workaround? What's the next best option besides Move for constantly updating the live location?

**Comment by jpmens** [comment]
@GitHubQueenn you are commenting on an issue which has been closed for four (!) years.

Significant changes is the mode your iPhone friend wants.
