### ISSUE TITLE
OwnTracks doesn't recognise being in region

### ISSUE THREAD

**Issue by arturum** [owntracks/ios#590]
Hi,
I have a strange behavior of OwnTracks on iPhone 6 (iOS 12.4 beta) - it doesn't see if the device is entering, leaving or is inside the region. There's no "transition" messages, no "inregions" attributes and on the map region which I'm obviously in is still blue-ish.
It doesn't matter if the regions were created manually or uploaded with config file. The number of them doesn't seem to play a role either (doesn't matter if there's 30 of them or only one).
I know that iOS is responsible for geofencing, not the app itself, but what might be the problem?

Regards
A.

**Comment by jpmens** [comment]
I have to ask: you have verified that the app is allowed access to location data, and you have verified that the app is in _Significant change_ mode (i.e. the "play" button is visible in the UI)?

**Comment by ckrey** [comment]
OwnTracks works fine on iOS 12.4 official. Please upgrade to official release.
We experienced some strange behavior in the past after iOS upgrades which were be solved by rebooting the device.

**Comment by arturum** [comment]
Thanks for speedy reaction.
I've upgraded te device to official ios release - same thing.
Obviously app is allowed to access location data :) It is in Significant change mode also. It doesn't really matter though - it seems to ignore regions in every mode. Even when it's in foreground and I'm obviously inside the region the color of the circle doesn't change, messages don't include "inregions" parameter.
Same thing on my iPad (unfortunately it's also beta - ipados). So I came to wonder if there's something wrong with my configurations. Is there an option to include/disregard geofencing (BTW maybe it's worth to add it)?  Or maybe other options influence this feature? For instance I don't use TLS encryption. I know that it's probably a long shot, but who knows what's connected to what in iOS...
<img width="375" alt="20190729_095736108_iOS" src="https://user-images.githubusercontent.com/53419481/62039526-38f67000-b23b-11e9-8c10-f1d348c1a1d1.png">

**Comment by arturum** [comment]
A small addendum: I found the similar issue reported here 5 years ago... https://github.com/owntracks/ios/issues/26

Exception is - mine still doesn't work. I've chcecked through iOS settings if they didn't introduced any exceptions to CLCircularRegion objects behaviour in recent iOS versions but no. My only guess is that there is some problem on my devices with passing the objects from app to the system or with app not receiving region-related notifications from system. I'd rule out (for now at least) problems with GPS connection, because the behaviour I observe is also when app is in full "vigilant" mode, with Wifi connected and GPS (acc 10) working - it still doesn't report that devices are inside circular region nor reporting leaving/entering the region.
I tested it also with different region radii - even 5000 meters isn't sufficient enough for the app to notice I'm inside... I'd be glad for some tips

**Comment by arturum** [comment]
Well. I figured it out I believe.
In config (otrc) file there is a "ranging" parameter, which according to Owntracks booklet affects Beacon ranging in iOS. But it seems that at least in my os versions it affects whole of Region Monitoring feature. Setting it to "true" (I believe that default value is "false" because I can't remember changing it, solved the issue.

**Comment by arturum** [comment]
Sorry for this torrent of messages, but now I believe I know what the problem is. It is connected to the number of waypoints - contrary to what I thought at the beginning. I have a massive number of waypoints in the config file (150 of them). An app works properly up to approx. 120. Moreover, the crash I observed and reported as #591  is also connected to the number of waypoints (or size of the config file). When it's more then 120, app crashes when trying to open the file (although all the waypoints are properly imported when I open the app again).

Now the question is, can this limit be lifted. I understand that you've implemented the solution suggested by Apple to bypass the 20 monitored regions per application limit imposed by iOS, as it seems that app works properly with much larger number. Is this 120 limit implemented in app itself, or is it influenced by other factors?

**Comment by ckrey** [comment]
Nothing is implemented to bypass the 20 monitored regions per application limit.
The app itself does not limit the number of regions.

**Comment by arturum** [comment]
To sum it up, there are two issues connected with large number of waypoints:
- when the number is larger then 20, app doesn't keep track of all of them, as per Apple imposed limit of monitored regions per app. iOS will store only the "oldest" ones - the rest is ignored and hence can't report transitions (entering and leaving) in the rest of regions. Apple's suggestion is to implement a mechanism to dynamically change the list of 20 regions passed to iOS to those closest to device's current position.
- when the number of waypoints imported to app by MQTT message or by opening the config file is larger then 120, the app crashes, but all the waypoints are saved, when you open the app again.

**Comment by jpmens** [comment]
@arturum thank you for summarizing your issue.

Please be so kind as to elaborate and explain what you are attempting to do, as the very large number of waypoints seems excessive to us.

**Comment by arturum** [comment]
@jpmens : I'm working with the charity organisation which helps seniors in their homes. I've been trying for some time to find a good solution to monitor our volunteers timesheets. There are some 40 volunteers and over 100 seniors. I needed a solution which is "gentle" for volunteers' devices in terms of battery and data usage - collects the significant positions of devices (times of entering and leaving the seniors' premises are sufficient enough) and when the device is able to connect (as in the range of known WiFi), sends the "report" for me to process it. It wasn't crucial for me to  know the positions of volunteers in real time. The other requirement was to minimize the need of volunteers operations (they are not that technology orientated :))
I found OwnTracks features closest to my needs.
I managed to override the problem with large number of waypoints for now by preparing individual waypoints MQTT messages (or files) for each volunteer, based on their roster, but it isn't ideal - roster changes constantly and sometimes there are situations when they go to someone who wasn't rostered previously. Then I would need volunteers to at least activate the app and connect device to internet to receive a new waypoints collection. So the best way to control this would be to "upload" the same collection of waypoints to all the devices initially with config file and change it later only occasionally - for example when the new client is appointed.

BTW the only other thing that OwnTracks lacks in terms of my purpose is some kind of scheduling mechanism - for volunteers to be sure that I'm not monitoring their after hours activities... Say that app should only gather and publish their positions on Mondays and Thursdays between 9am to 6pm. But this is completely separate thing from the topic of this thread.

Thanks for interest!

**Comment by jpmens** [comment]
@arturum thank you for your explanation.

You have an interesting project going, but we feel that what you are trying to accomplish goes above and beyond what we can do as part of our small Open Source project. OwnTracks for iOS works fine for most of our users with a reasonable amount of waypoints.

If you are interested in talking to us to implement some of these features for you, please don't hesitate to contact us at support@owntracks.org. 

I will now close this issue.
