### ISSUE TITLE
Shortcuts no longer switching mode when phone is locked

### ISSUE THREAD

**Issue by kirichkov** [owntracks/ios#740]
I can't pinpoint what is causing this, as the app's update coincided with an iOS update. I have an iOS shortcut that changed to 'move' mode when the phone was plugged in a charger and changed to 'significant' when the phone was disconnected from a charger. This shortcut no longer works when the phone is locked and I get the following error on the lock screen: `could not open "Owntracks" because the iPhone is locked.`

I'm fairly certain, this shortcut used to work just a few weeks ago, and I'm suspecting it is the iOS update that changed this behavior. Now, when the phone is unlocked it launches the application, and I think before the mode change happened without bringing the application to the front.

**Comment by ckrey** [comment]
Thank you @kirichkov for spotting this. I did change the internal processing of shortcuts with the last release to solve some other problems. I will review the mode change shortcut

**Comment by ckrey** [comment]
Test version 16.4.0 will be available in TestFlight soon

**Comment by kirichkov** [comment]
I'll install it when it appears and report back.

**Comment by kirichkov** [comment]
Changing monitoring mode is fixed, however “send location” still exhibits the issue. Likely the other actions (send tag/POI) also exhibit the issue, but I can’t test them.

**Comment by kirichkov** [comment]
Fixed in the last beta (16.4.1)!  Thank you for the quick reaction!

**Comment by jbrepogmailcom** [comment]
I still have this problem as of now. It seems that my older phone SE 2020 (with latest iOS 17) kills the app aggressively and it does not change mode from Shortcuts if it is killed (need to be woken up by significant move first perhaps?)

**Comment by ckrey** [comment]
Please don`t comment on old, closed issues. It doesn‘t work! see #766
